[33mcommit a6c7fcaa08be6f9078663654fa4cb07f2cea8c41[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmain[m[33m)[m
Author: Angelica Casotto <a.c.casotto@tudelft.nl>
Date:   Thu May 1 14:24:39 2025 +0200

    Added some precies

[33mcommit 53ba76cad0cccf6ae3d4974a71ca7f577b799267[m
Author: Angelica Casotto <a.c.casotto@tudelft.nl>
Date:   Thu May 1 14:02:20 2025 +0200

    Added some cake recipies

[33mcommit f48e5500c7542243374ff5f1ab5d3bd2eda93f20[m
Author: Angelica Casotto <a.c.casotto@tudelft.nl>
Date:   Thu May 1 13:53:38 2025 +0200

    Modify ingredients to the traditional recipe

[33mcommit de974ceed4369d7c48904515014db1d2f3f36813[m
Author: Angelica Casotto <a.c.casotto@tudelft.nl>
Date:   Thu May 1 13:46:55 2025 +0200

    Add ingridients to base recipe

[33mcommit bc053461a546ac979b0b077d3dd99f7dc712e793[m
Author: Angelica Casotto <a.c.casotto@tudelft.nl>
Date:   Thu May 1 13:37:26 2025 +0200

    Create initial outline for a gucamole recipe
